with-expecter: True
dir: '{{.InterfaceDir}}/mocks'
mockname: 'Mock{{.InterfaceName}}'
outpkg: 'mocks'
filename: 'Mock{{.InterfaceName}}.go'
all: True
packages:
  github.com/angristan/spotify-search-proxy:
    config:
      recursive: True
