app = "spotify-search-proxy"
primary_region = "cdg"

[env]
  PORT = "8080"

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]
